### ISSUE TITLE
How to set the DBRef property ref parameter value of a schema that is to be extended using extendSchema?

### ISSUE THREAD

**Issue by MohRaouf** [Josuto/monguito#187]
**Describe the bug**
Just an inquiry about the model name that is being used in case of reference to other collection

**To Reproduce**
```
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const ReferencedSchema = new Schema({
  // Define fields for the referenced collection
});

const ReferencedModel = mongoose.model('ReferencedModel', ReferencedSchema);

module.exports = ReferencedModel;

/*******************************/

const MainSchema = new Schema({
  referencedField: { type: Schema.Types.ObjectId, ref: 'ReferencedModel' },
});
```

I want to get the model name for schemas created by extendSchema, same as the mongoose way above !

**Comment by Josuto** [comment]
Hi @MohRaouf! 

Many thanks for your question. I'm however unsure about how can I help you. Are you trying to set the value of `ref` to be the result of `extendSchema`? I'd very much appreciate if you could elaborate your question a bit more 😉.

On the topic of _MongoDB References_, `monguito` should deal with [manual references](https://www.mongodb.com/docs/manual/reference/database-references/#manual-references) just fine. Dealing with [DBRefs](https://www.mongodb.com/docs/manual/reference/database-references/#dbrefs), however, is another story; I have not experimented with them just yet. 

I'm thinking about leveraging `DBRefs` to enable `monguito` users to declare relationships between documents of different collections. Do you like that idea yourself? 😃

**Comment by MohRaouf** [comment]
HI again @Josuto 
Thank you for your reply, 
let me explain more about what I want, 
I used to use mongoose where schemas that have reference to other schema can be defined as the following: 

```
const ReferencedSchema = new mongoose.Schema({
  // Define fields for the referenced collection
});

const ReferencedModel = mongoose.model('ReferencedModelName', ReferencedSchema);

/*******************************/

const MainSchema = new Schema({
  referencedField: { type: Schema.Types.ObjectId, ref: 'ReferencedModelName' },
});
```

in monguito when using extendSchema I don't define the model name which in the above example `ReferencedModelName`
so how to build a schema using extendSchema which has ref field requires model name from another model/schema that is built using extend schema too 

e.g. 
```
const refSchema =  new mongoose.Schema();
const RefSchema= extendSchema(BaseSchema, refSchema .obj);

const testSchema= new mongooseSchema<Test>({
        referencedField: { type: Schema.Types.ObjectId, ref: '?????' },
});

const TestSchema= extendSchema(BaseSchema, testSchema.obj, { timestamps: true });
```

**Comment by Josuto** [comment]
Hey @MohRaouf!

Thanks for you clarification. In a nutshell, the name for `ref` should be the name of the persistable domain class you want to reference in the schema of another persistable domain class. It is important that the definition of such a persistable domain class implements `Entity` or includes an `id` field so that `BaseSchema.toObject` can do its job of including a value for it during instance deserialisation.

Let me now explain what I mean by giving you a concrete example you can relate to. Let's also try to keep it simple; if your use case is however more complicated, please share it with me so that I can help you with it. 

Consider we have an `Author` domain class you want to reference in a `Book` class. Here is how I would create the required schemas:

```
const AuthorSchema: Schema<Author> = extendSchema(BaseSchema, {
    name: { type: String, required: true },
});

const BookSchema: Schema<Book> = extendSchema(BaseSchema, {
    title: { type: String, required: true },
    author: { type: Schema.Types.ObjectId, ref: 'Author' },
});
```

When defining MongoDB DBRefs, what is important is that you focus on the persistable domain class you want to reference; any other schema definition is irrelevant. Moreover, I want to stress that it is important that both `Author` and `Book` specify an `id` field for the aforementioned reason.

Hope this explanation was helpful to you. Otherwise, please insist with your question and I will do my best to help you out 😊.
